input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # Здесь можно добавить grok, mutate, date, geoip и т.д.
}

output {
  elasticsearch {
    hosts => [
      "https://es-data-1:9200",
      "https://es-data-2:9200",
      "https://es-data-3:9200"
    ]

    cacert => "/usr/share/logstash/certs/elk-stage.crt"

    index => "logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}